language: go
go: 1.6
sudo: required
env:
- GROUP=weaveworksdemos COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG
services:
- docker
- mongodb
script:
- make test
- make coverprofile
- make dockertest
install:
- make deps
after_success:
- go get -v github.com/mattn/goveralls
- goveralls -coverprofile=cover.profile -service=travis-ci
- make dockertravisbuild
before_install:
- openssl aes-256-cbc -K $encrypted_7c540e2aa1cb_key -iv $encrypted_7c540e2aa1cb_iv
  -in user_deploy_rsa.enc -out user_deploy_rsa -d
addons:
  ssh_known_hosts: $BASTION
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/user_deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/user_deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o StrictHostKeyChecking=no ${BASTION_USER}@${BASTION} ./deploy.sh user $COMMIT
  on:
    branch: master
